
services:

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  
  app:
    build: .
    depends_on:
      - mongo
    links:
      - mongo
    ports: 
      - 3000:3000

volumes:
  mongo_data:
