version: "3.9"
services:
  app:
    build: .
    container_name: ejercicio2_app
    ports:
      - "8081:3000"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: ejercicio2_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: usuariosdb
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db_data:
