
services:
  app: 
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USER=userapp
      - DB_PASSWORD=12345
      - DB_NAME=db_usuarios
      - DB_PORT=3306
    volumes:
      - .:/app
      - /app/node_modules

  mysql: 
    image: mysql:8
    container_name: mysql_e2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_usuarios
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

    

volumes:
  mysql_data:
