version: "3.8"
services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=metrics
      - INFLUXDB_USER=admin
      - INFLUXDB_USER_PASSWORD=admin123
    networks:
      - ticks

  telegraf:
    image: telegraf:1.28
    container_name: telegraf
    depends_on:
      - influxdb
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    ports:
      - "8080:8080"
    networks:
      - ticks

  chronograf:
    image: chronograf:1.10
    container_name: chronograf
    ports:
      - "8888:8888"
    depends_on:
      - influxdb
      - kapacitor
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - KAPACITOR_URL=http://kapacitor:9092
    networks:
      - ticks

  kapacitor:
    image: kapacitor:1.6
    container_name: kapacitor
    environment:
      - KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086
    ports:
      - "9092:9092"
    depends_on:
      - influxdb
    volumes:
      - ./kapacitor:/etc/kapacitor
      - ./kapacitor/tick_script.tick:/var/lib/kapacitor/tick_script.tick 
    networks:
      - ticks

  microservicio:
    build: ./microservicio
    container_name: microservicio2
    ports:
      - "4000:4000"
    networks:
      - ticks

networks:
  ticks:
    driver: bridge
