version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  producer:
    build: ./producer
    container_name: producer
    ports:
      - "3000:3000"
    env_file:
      - ./producer/.env
    depends_on:
      - rabbitmq

  consumer:
    build: ./consumer
    container_name: consumer
    env_file:
      - ./consumer/.env
    depends_on:
      - rabbitmq
